import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {House, ShoppingBag, User} from "lucide-react";
import Link from "next/link";
import clsx from "clsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const query ="abc123";

  return (
      <html lang="en">
      <body
          className={clsx(
              geistSans.variable,
              geistMono.variable,
              'antialiased pt-[40px]',
          )}
      >
        {children}


        <div
            className={clsx(

                "bg-black text-white bottom-0 sticky",
                "flex justify-between py-[50px] px-[50px]",
            )}
        >
            <Link href={"/"}>
                <House/>
            </Link>
            <Link href={"/shop"}>
                <ShoppingBag/>
            </Link>
            <Link href={"/shop/test"}>
                Test 1
            </Link>
            <Link href={"/shop/test2?id=2"}>
                Test 2
            </Link>
            <Link href={"/shop/test3?id=2"}>
                Test 3
            </Link>
            <Link href={"/shop/test4?id=2"}>
                Test 4
            </Link>
            <Link href={`/shop/working?search=${query}`}>
                Working
            </Link>
            <Link href={"/user"}>
                <User/>
            </Link>
        </div>

      </body>
    </html>
  );
}
